spring:
    application:
         name: Rest-Operator
    config:
      import:
        optional:configserver:http://localhost:8084

eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka/  
